Adds the DPCT generated codes, Makefile (without clang++ -fsycl) and slurm submit script for CSD3
UCL-ARC/openqcd-fastsum pull request #20
Opened 2022-03-09 13:02 UTC by krishnakumarg1984

- adds dpct generated sycl codes for cuda2 version
 - adds a Makefile (outdated). Needs to be updated with the nightly build of open-source dpcpp
 - adds a slurm submit Makefile
 - Updates to gitignore

2022-03-09 14:22 UTC, tkoskela requested changes
Thanks for opening the PR, I think we can close #13 once this is merged. It looks to me as if there are still a few extra files that could be cleaned up before merging.

I also added a suggestion to make the Makefile a bit more flexible, but I'm very open to other ideas as well.

We may have to think a bit about the directory structure. I think we can keep the source code and the Makefile in `dpct_output` for now, but I would keep job scripts and such in a separate directory. Perhaps create a directory called `extra` under `tests/cuda2`, what do you think?

2022-03-09 14:22 UTC, tkoskela commented on tests/cuda2/dpct_output/Makefile
> +	$(CC) $(INCLUDES) $(CFLAGS) $^ -o $@
We will need to be able to use the Makefile to build with different compilers and architecture targets. I can use this one if I invoke it with

```
make CC=clang++ CFLAGS="-O2 -Wall -fsycl -fsycl-targets=nvptx64-nvidia-cuda"
```

but it feels a bit cumbersome. At the least we will need to document the commands we are using. Do you have any ideas how to improve it?

One way would be following [this stackoverflow thread](https://stackoverflow.com/questions/13358131/one-makefile-for-two-compilers) set `CC` and `CFLAGS` for each target and then have separate targets for `intel` and `nvidia`.

```suggestion
CC=dpcpp
CFLAGS=-O2 -Wall
LDFLAGS=
INCLUDES=-Iincludes

intel: CC = dpcpp

nvidia: CC = clang++
nvidia: CFLAGS += -fsycl -fsycl-targets=nvptx64-nvidia-cuda

all: intel nvidia

intel: main.c dw_cuda_soa.dp.cpp read_in.c
	$(CC) $(INCLUDES) $(CFLAGS) $^ -o main
	
nvidia: main.c dw_cuda_soa.dp.cpp read_in.c
	$(CC) $(INCLUDES) $(CFLAGS) $^ -o main	
```

2022-03-14 10:39 UTC, krishnakumarg1984 commented on run/input.in.txt
> +
Done.

2022-03-14 10:42 UTC, krishnakumarg1984 commented on extra/rename_bin_files.sh
> +done
Yes. Agree. Removed this file.

2022-03-14 10:45 UTC, krishnakumarg1984 commented on build/compile_settings.txt
> +LDFLAGS -g
Yes. Maybe worth taking notice that LDFLAGS has a `-g` option passed to it. Reverted this change.

2022-03-14 10:51 UTC, krishnakumarg1984 commented on tests/cuda2/dpct_output/Makefile
> +	$(CC) $(INCLUDES) $(CFLAGS) $^ -o $@
I think it's best to write a CMakelists.txt that will handle this. Is it important to get to that before March 31, 2022?

2022-03-14 10:54 UTC, krishnakumarg1984 commented
> Perhaps create a directory called `extra` under `tests/cuda2`, what do you think?

Yes. I agree that the directory structure we currently have is not very intuitive (it's too deeply nested and not discoverable).

Putting stuff under `extra` maybe subtly conveys that it is not directly useful to the project? What kind of scripts should go into extras?

2022-03-14 23:27 UTC, merged